vpc_cidr_block = "10.0.0.0/16"
public_subnet_cidr_blocks = ["10.0.1.0/24"]
private_subnet_cidr_block = ["10.0.3.0/24","10.0.2.0/24"]
availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
vpc_name = "dev-vpc"
environment = "dev"
aws_region = "eu-west-1"
public_subnet_names = ["public-subnet-1","public-subnet-2","public-subnet-3"]
private_subnet_names = ["private-subnet-1","private-subnet-2","private-subnet-3"]